// Code generated by MockGen. DO NOT EDIT.
// Source: internal/company/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/company/usecase.go -destination=internal/company/mocks/company_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
